### ISSUE TITLE
Multiline comments are not renderes properly

### ISSUE THREAD

**Issue by chris99plus** [Fair-Bytes/aapi-codegen#1]
Description of properties which have multiple lines fail to render in the model.go file.

```yaml
test:
    type: boolean
    description: |
        This is a multiline
        description, which does not render properly.
```
